# -*- coding: utf-8 -*-
"""cv4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IwZ3-0QVah7H1UGHVHzy0GL6Stw7Cu4P
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
#Function to display image
def show_comparsion(original,sobel,prewitt,canny):
  plt.figure(figsize=(12,10))
  plt.subplot(2,2,1)
  plt.imshow(original,cmap='gray')
  plt.title('Original grayscale image')
  plt.axis('off')
  plt.subplot(2,2,2)
  plt.imshow(sobel,cmap='gray')
  plt.title('Sobel edge detection')
  plt.axis('off')
  plt.subplot(2,2,3)
  plt.imshow(prewitt,cmap='gray')
  plt.title('Prewitt edge detection')
  plt.axis('off')
  plt.subplot(2,2,4)
  plt.imshow(canny,cmap='gray')
  plt.title('Canny edge detection')
  plt.axis('off')
  plt.tight_layout()
  plt.show()

#1.read an image
img = cv2.imread('/content/heidi',0)
if img is None:
  print("error:image not found")
else:
    #--sobel operator--
    #gradient in x and y direction
    sobelx = cv2.Sobel(img,cv2.CV_64F,1,0,ksize=3)
    sobely = cv2.Sobel(img,cv2.CV_64F,0,1,ksize=3)
    #combine gradients
    sobel_combined = cv2.bitwise_or(sobelx,sobely)
    #--prewit operator--
    #define kernels (Px,Py)
    kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]])
    kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
    #apply kernel using filter2D
    prewitx = cv2.filter2D(img, -1, kernelx)
    prewity = cv2.filter2D(img, -1, kernely)
    prewit_combined = prewitx + prewity
    #--canny edges setection--
    # arguments: image,threshould1,threshould2
    canny_edges = cv2.Canny(img,100,200)
    show_comparsion(img,sobel_combined,prewit_combined,canny_edges)